### PR TITLE
WHIPPINGDOT CHOINGES

### PR DESCRIPTION
**Pull request by whippingdot**
This is the PR for changes that I make. I will first push it here, then rebase to main.

P.S. for commit https://github.com/whippingdot/Language-Tutorials/commit/df7480f8afc1f8e74d81387fb9e4043d2fe8edfb @CrimsonCodes0 gave the base template and I just changed it cause progress was not being made. I forgot who made it and so I didn't add him as a co-author, sorry.

### CODE REVIEW

**Comment by CrimsonCodes0** [comment]
Using "parameter" instead of "attribute" in the function section would be a good start.

**Comment by whippingdot** [comment]
> Using "parameter" instead of "attribute" in the function section would be a good start.

??? I thought functions use attributes

**Comment by CrimsonCodes0** [comment]
They do, but you talked about parameters, while calling them "attributes." Can you show an example of both to make sure that we're both on the same page?

**Comment by whippingdot** [comment]
An attribute -
```cpp
#include <iostream>

int aFunc(int attribute)
{
	return attribute + 1;
}

int main()
{
	int teAttribute = 1;

	std::cout << aFunc(teAttribute) << std::endl;
}
```

```shell
2
```

_Oh and you reminded me - I need to talk about where functions can be defined - below and on top. I personally use below_

**Comment by CrimsonCodes0** [comment]
...and do you know what a parameter looks like?

**Comment by CrimsonCodes0** [comment]
Refer to what I had said in comment https://github.com/whippingdot/Language-Tutorials/commit/df7480f8afc1f8e74d81387fb9e4043d2fe8edfb#r49811524.

**Comment by whippingdot** [comment]
can you explain what a parameter is lul sorry?

I feel like both of them are the same...

**Comment by CrimsonCodes0** [comment]
They're entirely unrelated:
```c++
[[attribute]] T function(H parameter);
```

**Comment by whippingdot** [comment]
O ok i will lul

**Comment by whippingdot** [comment]
> You'd be better off opening the links in the comment that I had referenced. 

I checked them out now. I am going to change that part and also make a few more changes now.

**Comment by whippingdot** [comment]
Hey can I rebase yet? Also is cherry picking and rebasing the same?

@CrimsonCodes0 pls review this

**Pull request merged**
