### PR TITLE
New operator

### PR DESCRIPTION
**Pull request by darkdarcool**
Added new operator to the readme.

It divides and returns a whole number, it is for division that just rounds so you can't get a number that has decimals, use [this link](https://www.w3schools.com/python/trypython.asp?filename=demo_oper_floordiv) to see a small example on it, I think that I'll just review this repo every now and then to make sure you got everything and did it right!

Cheers!

### CODE REVIEW

**Comment by whippingdot** [comment]
First of all, cool but you missed the output so ima update and commit it. Second of all why did you copy @frissyn's profile picture? Change it back to the dark shadow dude - I liked it better

**Comment by darkdarcool** [comment]
lol I liked it and my friend had it on discord, and people were asking if I was a drug dealer, and that picture didn't really reflect my personality, I'll change it soon, but for now I'll keep it like this.(plus frissyn changed his profile picture).

Also for every operator in python go [to this](https://www.w3schools.com/python/python_operators.asp)

Also maybe I could do a coding language here, this seems like a good idea and I feel like I can contribute more?

**Comment by whippingdot** [comment]
wdym do a coding language here? Also I mistakenly created a new branch so I am gonna create a PR and merge. You can close this PR when you want to

**Comment by whippingdot** [comment]
Also do you want to be invited to this project?

**Comment by darkdarcool** [comment]
sure,  I feel like I can document ruby, c, or java(or c sharp(c#)) ok

**Comment by whippingdot** [comment]
ima star this repo later so it gets attention. I hope more people join and this is useful

**Comment by darkdarcool** [comment]
kk, also your making this on visual studio code, I have that and if you use (https://code.visualstudio.com/blogs/2017/11/15/live-share) that we can do it together live?

**Comment by whippingdot** [comment]
ya, if you want to

**Comment by darkdarcool** [comment]
kk

**Comment by whippingdot** [comment]
Ima send a link here to join the session. Tell me when you joined, I will delete it

**Comment by darkdarcool** [comment]
kk, it mighty take me a while, I am on the wrong computer, so give me like 10 min, I will make a comment here when I am on the right computer

**Comment by whippingdot** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?7F2496F14A5E453BFAC34867F581956B6632

**Comment by whippingdot** [comment]
join when ready. I have exams, I gotta study. We can just add like a few more pages, then I have to study. Sorry

**Comment by whippingdot** [comment]
@darkdarcool u there? I might have to go now...

**Comment by whippingdot** [comment]
https://github.com/whippingdot/Language-Tutorials/invitations my invite to you

I have to leave now...@BD103 if u wanna join just comment here. Also star this repo if you think it is useful! 😊

**Comment by darkdarcool** [comment]
alright I am here now!

**Comment by whippingdot** [comment]
I have to leave now, sry. Just join the repo (i invited you), and code whenever you want.

P.S. I am going to create a recommended extensions for VS Code folder, which will have the One Dark Pro theme and the Markdown All in One extensions.

**Comment by darkdarcool** [comment]
kk cool, will install, will try to be on earlier tomorrow.

**Comment by darkdarcool** [comment]
btw, I installed one dark pro and markdown all in one! Looks kewl

**Comment by darkdarcool** [comment]
also @whippingdot, install https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker to catch spelling errors.

**Comment by whippingdot** [comment]
> also @whippingdot, install https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker to catch spelling errors.

already have it BOI

**Comment by darkdarcool** [comment]
nice

**Comment by whippingdot** [comment]
hey im back wanna code?

**Comment by whippingdot** [comment]
only for 15 mins. I have a lot to study

**Comment by darkdarcool** [comment]
yeh

**Comment by darkdarcool** [comment]
would be great, code plz

**Comment by darkdarcool** [comment]
ill give code actually

**Comment by whippingdot** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?E22EB16FAA1BD27CB0D2F7BAD136AA57D280

**Comment by whippingdot** [comment]
Tell me when you join

**Comment by whippingdot** [comment]
> ill give code actually

I did it already

**Comment by darkdarcool** [comment]
kk

**Comment by whippingdot** [comment]
did you join? Can I remove the link?

**Comment by darkdarcool** [comment]
im there, I don't want to do audio

**Comment by whippingdot** [comment]
me too, oops. I disabled audio. I don't see u

**Comment by whippingdot** [comment]
U ter

**Comment by darkdarcool** [comment]
i don't see you either, and don't do auto, and I can't make any files

**Comment by darkdarcool** [comment]
Screen Shot 2021-03-16 at 10 27 13 AM
That's what I see

**Comment by whippingdot** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?E22EB16FAA1BD27CB0D2F7BAD136AA57D280

**Comment by whippingdot** [comment]
bruh it isn't working. It is ok, maybe later.

**Comment by darkdarcool** [comment]
kk, wiat,  I see you

**Comment by whippingdot** [comment]
check the chat

**Comment by darkdarcool** [comment]
where is the chat?

**Pull request merged**
