### PR TITLE
Small Change

### PR DESCRIPTION
**Pull request by darkdarcool**
Made a small change so you don't give the `var` variable any value in the cpp tutorial!

### CODE REVIEW

**Comment by whippingdot** [comment]
nope it is bad practice to keep a variable undefined in python and C++

**Comment by darkdarcool** [comment]
uhh, in all of my time learning in cpp, every instructor has told me if you are going to leave a variable blank, you might as well not sign it a value, and how is it bad practice? Yo are still leaving the variable with the same data as you would if you didn't give it a clue, and with fewer character to type?

**Comment by JBYT27** [comment]
Guyyysss! Stop clogging up my emailss!!! Lol

**Comment by darkdarcool** [comment]
lol sorry jb, and I also got your package to work: https://pypi.org/project/REPLAPI/

**Pull request closed without merging**
