### PR TITLE
[WIP] Github Spell Check Action

### PR DESCRIPTION
**Pull request by darkdarcool**
This is a simple action that I found that checks out spelling for people who are making edits in code editors that don't have spell checkers. This is mainly used for pull requests, but is also done on commit to make sure we are using proper spelling. If anyone can find a grammar checker, this would be a good place to put it!

### CODE REVIEW

**Comment by whippingdot** [comment]
Can you show me an example of how this works in this current PR itself? Maybe make an edit with spelling mistakes and I can see what it says / does.

**Comment by darkdarcool** [comment]
hmmmmmm sure. lemme try to make a repository with spelling mistakes. I'll get back to you.

**Comment by darkdarcool** [comment]
Ok, so if you go to https://github.com/darkdarcool/Test_SpellCheck. You can see that my md has intentional spelling errors. So when you click on the runs for the action, click on the one that failed, and go to the bottom of that part of the action. It's says my md has spelling errors. So, I'm still looking for better spell checkers. But this one does it the best so far!!

**Review by JBYT27 — APPROVED** [review]
Very noice!

**Comment by whippingdot** [comment]
Umm sorry I wouldn't add this as it doesn't tell you WHAT errors there are. You would have to manually loook through the files and see what spelling mistakes there were.

Also a must need is to be able to add certain spellings as correct.

**Comment by darkdarcool** [comment]
@whippingdot, I'm still looking for better ones. But this is the best one I have found so far. If you find a better one. Please give me the link to the github action and I'll test it.

**Comment by darkdarcool** [comment]
> Also a must need is to be able to add certain spellings as correct.

We may not be able to do that, but I'll try to find one.

**Comment by whippingdot** [comment]
no like or else some spellings that we made ourselves (Like names) will be marked as wrong whenever we open a PR

**Comment by darkdarcool** [comment]
ik. I will try to find one like that. But I can't guarantee anything.

**Comment by cursorweb** [comment]
does this work for things like:
pog

or really really really non-used words like:
bronchogenic carcinomas

**Comment by darkdarcool** [comment]
i mean. I didn't test that. I'm still finding good spell checkers. Feel free to look and test for one yourself.

**Comment by JBYT27** [comment]
hm

**Comment by whippingdot** [comment]
in the end, I don't think this is needed

**Comment by JBYT27** [comment]
huh, okie

**Comment by darkdarcool** [comment]
ah ok

**Pull request closed without merging**
