### PR TITLE
Add "5. Scoping and Functions" to the C++ tutorial

### PR DESCRIPTION
**Pull request by ghost**
Adds a new file to the C++ tutorial.

Based the file off of the functions file in Python, but the explanations will be very different.

Some things I'll mention:
Scoping:
[ ] - Use
[ ] - Variable visibility
Functions:
[ ] - Use
[ ] - Syntax
[ ] - Types
~~[ ] - Exception specifiers~~
[ ] - Call stacks
[ ] - UB (failure to return)

(I'll add to these lists as appropriate)

### CODE REVIEW

**Comment by whippingdot** [comment]
wait before functions we need loops. If loops, while loops, and for statements. @Rayyan06 is already making his own changes to the tutorial to include those before the functions file. You need to add those first.

**Comment by CrimsonCodes0** [comment]
@whippingdot
And what about if/else statements?

But, if I may ask, why would they need to come first?

```c++
auto square(double const x) {
    return x * x;
}
```

No loops necessary, afaict.

Regardless, I'll write it up, but re-order it when they're done.

**Comment by whippingdot** [comment]
> @whippingdot
> 
> And what about if/else statements?

Oops mistake in what I wrote. I meant while loops, for loops, and if statements.

**Comment by darkdarcool** [comment]
seems fine to add

**Comment by CrimsonCodes0** [comment]
Whoa, this is far from done, and still a WIP.

**Comment by darkdarcool** [comment]
ik, it just looks good rn

**Comment by CrimsonCodes0** [comment]
@whippingdot Wait, if/else statements and loop statements create scopes in each `{ ... }`, which is part of what I'm covering here, so shouldn't *this* come first?

**Comment by whippingdot** [comment]
Bruh maybe just add the part about curly braces in the loops file. It's that easy

**Comment by CrimsonCodes0** [comment]
It's more than just the fact that they both use curly braces, it's that the language constructs create scopes.

Scopes are a fundamental that loops and if/else depend upon, so it only makes sense to go scope -> if/else or loop, and not the other way around. Does anyone disagree?

**Review by darkdarcool — APPROVED** [review]

**Comment by whippingdot** [comment]
> It's more than just the fact that they both use curly braces, it's that the language constructs create scopes.
> 
> Scopes are a fundamental that loops and if/else depend upon, so it only makes sense to go scope -> if/else or loop, and not the other way around. Does anyone disagree?

fine, then create a file on scopes? If your really think putting functions first is necessary, then put them first. I don't really care.

**Comment by CrimsonCodes0** [comment]
I've been writing this on mobile, it's significantly harder to swap tabs and compare formatting, I was going to reformat it later.

**Comment by CrimsonCodes0** [comment]
@darkdarcool You are aware that when you had said,
> ik, it just looks good rn

that I had less than 10 sentences in the file, right?

**Comment by whippingdot** [comment]
> ik, whenever it pings me to review something i do

no-one pinged you to review it tho...

**Comment by darkdarcool** [comment]
well i got a ping and it took me to the review page

**Comment by whippingdot** [comment]
Hey finish this please. I need to start reviewing these.

**Comment by CrimsonCodes0** [comment]
Sure thing, I'll get around to it within the week.

**Comment by whippingdot** [comment]
Hey are you going to work on this? For the moment I am going to add some of the features you have done so far in this pr in the main branch. I will add you as a co-author in every commit.

**Comment by CrimsonCodes0** [comment]
Sure, I can work on it today and tomorrow.

**Comment by CrimsonCodes0** [comment]
Closing in favor of commit https://github.com/whippingdot/Language-Tutorials/commit/df7480f8afc1f8e74d81387fb9e4043d2fe8edfb

**Comment by darkdarcool** [comment]
Finally this pull rqst was closed.

**Comment by darkdarcool** [comment]
[ x ] : Finish this pull rqst

**Pull request closed without merging**
